
CREATE TABLE PEDIDO_VENDA
(
    pedidovendaID INTEGER NOT NULL,
    cod_cliente NVARCHAR(160) NOT NULL,
    vendedorID INTEGER NOT NULL,
    cod_situacaoped NVARCHAR(160) NOT NULL,
    cod_forma_pagamento NVARCHAR(160) NOT NULL,
    CONSTRAINT PedidoVendas PRIMARY KEY (pedidovendaID),
    CONSTRAINT FK_vendedorID FOREIGN KEY (vendedorID) REFERENCES vendedor(vendedorID),
    CONSTRAINT FK_STTSPEDIDO FOREIGN KEY (cod_situacaoped) REFERENCES SITUACAO_PEDIDO(situacaopID),
    CONSTRAINT FK_FORMAPAG FOREIGN KEY (cod_forma_pagamento) REFERENCES FORMA_PAGAMENTO(formaPAGID),
    CONSTRAINT FK_CLIENTE FOREIGN KEY (cod_cliente) REFERENCES CLIENTE(clienteID)	
);

CREATE TABLE [vendedor]
(
    vendedorID INTEGER NOT NULL,
    telefone NVARCHAR(160) NOT NULL,
    endereco NVARCHAR(160) NOT NULL,
    nome NVARCHAR(160) NOT NULL,
    CONSTRAINT vendedor PRIMARY KEY (vendedorID)
);

CREATE TABLE [FORMA_PAGAMENTO]
(
	[formaPAGID] INTEGER  NOT NULL,
    [forma_pag] NVARCHAR(160)  NOT NULL,
    CONSTRAINT [PAG] PRIMARY KEY ([cod_formaPAG])

);

CREATE TABLE [CLIENTE]
(
	[clienteID] INTEGER  NOT NULL,
    [telefone] NVARCHAR(160)  NOT NULL,
    [endereço] NVARCHAR(160)  NOT NULL,
    [nome] NVARCHAR(160)  NOT NULL,
    CONSTRAINT [cliente] PRIMARY KEY ([clienteID])

);

CREATE TABLE [ITEM_PEDIDOVENDA]
(
	[itempedidovendaID] INTEGER  NOT NULL,
    [pedidovendaID] NVARCHAR(160)  NOT NULL,
    [cod_produto] NVARCHAR(160)  NOT NULL,
    [qtd_item_pedido] NVARCHAR(160)  NOT NULL,
    CONSTRAINT [ITEMPEDIDOVENDA] PRIMARY KEY ([itempedidovendaID]),
    CONSTRAINT [FKPEDIDO_VENDA]FOREIGN KEY (pedidovendaID)	REFERENCES PEDIDO_VENDA(pedidovendaID),
    CONSTRAINT [FKPRODUTO] FOREIGN KEY (cod_produto) REFERENCES PRODUTO(cod_Produto)
);

CREATE TABLE [PRODUTO]
(
	[cod_PRODUTO] INTEGER  NOT NULL,
    [cod_TIPOPRODUTO] NVARCHAR(160)  NOT NULL,
    [nome] NVARCHAR(160)  NOT NULL,
    [vlr_produtoC] NVARCHAR(160)  NOT NULL,
    [vlr_produtoV] NVARCHAR(160)  NOT NULL,
    CONSTRAINT [PRODUTO] PRIMARY KEY ([cod_Produto]),
    CONSTRAINT [FKcod_tipoP] FOREIGN KEY (cod_TIPOPRODUTO) REFERENCES TIPO_PRODUTO(cod_tipoP)
);

CREATE TABLE [ITEM_PEDIDOCOMPRA]
(
	[cod_itempedidoC] INTEGER  NOT NULL,
    [cod_pedidocompra] NVARCHAR(160)  NOT NULL,
    [cod_produto] NVARCHAR(160)  NOT NULL,
    [QTD_itempedidoV] NVARCHAR(160)  NOT NULL,
    CONSTRAINT [ITPCOMPRA] PRIMARY KEY ([cod_itempedidoC]),
	CONSTRAINT [FKPRODUTO] FOREIGN KEY (cod_produto) REFERENCES PRODUTO(cod_Produto),
	CONSTRAINT [FKPEDIDOCOMPRA] FOREIGN KEY (cod_pedidocompra)	REFERENCES PEDIDO_COMPRA(cod_PEDIDOCOMPRA)
);

CREATE TABLE [PEDIDO_COMPRA]
(
	[cod_PEDIDOCOMPRA] INTEGER  NOT NULL,
    [cod_FORNECEDOR] NVARCHAR(160)  NOT NULL,
    [VLR_PEDIDO_COMPRA] NVARCHAR(160)  NOT NULL,
    CONSTRAINT [PCOMPRA] PRIMARY KEY ([cod_PEDIDOCOMPRA])
    CONSTRAINT [FORNECEDORFK]	FOREIGN KEY (cod_FORNECEDOR)REFERENCES FORNECEDOR(cod_fornecedor)
);

CREATE TABLE [COTAÇÃO]
(
	[cod_COTACAO] INTEGER  NOT NULL,
    [cod_produto] NVARCHAR(160)  NOT NULL,
    [cod_fornecedor] NVARCHAR(160)  NOT NULL,
    [vlr_pedidoC] NVARCHAR(160)  NOT NULL,
    CONSTRAINT [COTACAO] PRIMARY KEY ([cod_COTACAO]),
    CONSTRAINT [FKPRODUTO] FOREIGN KEY (cod_produto) REFERENCES PRODUTO(cod_PRODUTO),
    CONSTRAINT [FORNECEDOR] FOREIGN KEY (cod_fornecedor) REFERENCES FORNECEDOR(cod_fornecedor)
);

CREATE TABLE[TIPO_PRODUTO]
(
	[cod_tipoP] INTEGER  NOT NULL,
    [descricao] NVARCHAR(160)  NOT NULL,
    CONSTRAINT [TPRODUTO] PRIMARY KEY ([cod_tipoP])
);

CREATE TABLE [FORNECEDOR]
(
	[cod_fornecedor] INTEGER  NOT NULL,
    [telefone] NVARCHAR(160)  NOT NULL,
    [nome] NVARCHAR(160)  NOT NULL,
    [endereço] NVARCHAR(160)  NOT NULL,
    [email] NVARCHAR(160)  NOT NULL,
    CONSTRAINT [FORNECEDOR] PRIMARY KEY ([cod_fornecedor])
);

CREATE TABLE [SITUACAO_PEDIDO]
(
	[situacaopID] integer NOT NULL,
	[STTS_PAG] NVARCHAR(160) NOT NULL,
	CONSTRAINT [CODSITUACAOP] PRIMARY KEY ([situacaopID])
	
	);
banco de dados.txt
Exibindo banco de dados.txt.


